services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      # - "67:67/udp"   # Uncomment if using Pi-hole as DHCP server
      # - "123:123/udp" # Uncomment if using Pi-hole as NTP server

    environment:
      TZ: "${TZ}"
      FTLCONF_dns_listeningMode: "ALL"
      WEBPASSWORD_FILE: "pihole_web_password"
      # FTLCONF_misc_etc_dnsmasq_d: "true"

    volumes:
      - ./config/pihole/etc-pihole:/etc/pihole
      # - ./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    secrets:
      - pihole_web_password

    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

    networks:
      home_network:
        ipv4_address: "${PIHOLE_IPV4_ADDRESS}"

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped

    ports:
      - "8080:80"
      - "8443:443"

    environment:
      TZ: "${TZ}"
      SEARXNG_HOSTNAME: "${SEARXNG_HOSTNAME}"

    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./config/caddy/data:/data
      - ./config/caddy/config:/config

    networks:
      - proxy_network

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped

    environment:
      TZ: "${TZ}"
      SEARXNG_BASE_URL: "${SEARXNG_BASE_URL}"
      SEARXNG_SECRET: "${SEARXNG_SECRET}"

    volumes:
      - ./config/searxng/:/etc/searxng/
      - ./config/searxng/data:/var/cache/searxng

    networks:
      - proxy_network

secrets:
  pihole_web_password:
    file: ./runtime/server01/secrets/pihole_web_password.txt

networks:
  home_network:
    driver: macvlan
    driver_opts:
      parent: "${PIHOLE_PARENT_INTERFACE}"
    ipam:
      config:
        - subnet: "${PIHOLE_SUBNET}"
          gateway: "${PIHOLE_GATEWAY}"

  proxy_network:
    driver: bridge
